name: compassionapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  table_calendar: ^3.1.2
  url_launcher: ^6.0.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  smooth_page_indicator: ^1.2.0
  flutter_xlider: ^3.4.0
  


  
flutter:
  uses-material-design: true
  assets:
    - assets/lang/dk.json
    - assets/lang/en.json
    - assets\images\compassion_focused_therapy.webp
    - assets\images\contact-self-compassion-background.webp
    - assets\images\hearths.jpg
    - assets\images\meditation.webp
    

