name: compassionapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  table_calendar: ^3.1.2
  url_launcher: ^6.0.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0
  youtube_player_flutter: ^9.1.1
  audioplayers: ^6.1.0
  google_maps_flutter: ^2.0.6
  geolocator: ^8.0.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  smooth_page_indicator: ^1.2.0
  flutter_xlider: ^3.4.0
  


  
flutter:
  uses-material-design: true
  assets:
    - assets/lang/dk.json
    - assets/lang/en.json
    - assets\images\compassion_focused_therapy.webp
    - assets\images\contact-self-compassion-background.webp
    - assets\images\hearths.jpg
    - assets\images\meditation.webp
    - assets\soundClips\Meditation_1_5_min_meditation.m4a
    - assets\soundClips\Oevelse_1_Angst_og_svaere_feolelser.m4a
    - assets\soundClips\compassion_background_app_ready.png
    

